### ISSUE TITLE
help exp command contains a typo

### ISSUE THREAD

**Issue by ngzhaoming** [AY1920S2-CS2103T-T10-3/main#232]
To re-create this:
1) Type in the command```help exp```
2) You should be able to notice this small typo error with the ```exp setsubget``` instead of ```exp setbudget```

<img width="1129" alt="Screenshot 2020-04-09 at 6 10 02 PM" src="https://user-images.githubusercontent.com/54199354/78896442-0f1c6b00-7aa3-11ea-81b5-06c958fd64c3.png">

**Comment by sp-shaopeng** [comment]
fixed
