### ISSUE TITLE
Being able to travel back time in the calendar

### ISSUE THREAD

**Issue by ngzhaoming** [AY1920S2-CS2103T-T10-3/main#234]
# The girl who leapt through time

### Introduction
This is a story about a girl who is able to travel back in time so much that she went off to the negative year. Wanna know the trick to this hax? Well, then read to find out more. The girl even took pictorial evidence of herself in a negative year.

### How it began
Type in this command and you will be filled with awe: `go -10001-05-30`
Find yourself in the year of negative. Furthermore, in the user guide, the format is YYYY-MM-DD. However, a negative year is allowed.

This can also be done through:
1) `go 0000-01-01`
2) Click on the left-hand side arrow to go back one month to -0001-12-31

### Conclusion
Try to limit the date to a range say, 1950 to 3000 so that it is harder to break such dates. You guys can also try `go 9999-12-31` and click next. I'm sure that it will be the year **10000**

<img width="1131" alt="Screenshot 2020-04-09 at 6 17 27 PM" src="https://user-images.githubusercontent.com/54199354/78898080-ca460380-7aa5-11ea-9f21-26c0705f44dc.png">

**Comment by sp-shaopeng** [comment]
![feature](https://user-images.githubusercontent.com/59863379/78898718-d67e9080-7aa6-11ea-928f-72766d096e95.jpeg)
Oracle is travelling back with me!
