### ISSUE TITLE
Unable to export/print in the report window

### ISSUE THREAD

**Issue by ngzhaoming** [AY1920S2-CS2103T-T10-3/main#236]
To recreate this bug:
1) In the main window call the command `report view -sd 2020-03-01 -ed 2020-03-31 -g bar -o month`. This should subsequently open the report window with the bar graph for that month being shown.
2) Subsequently, using `export file` will successfully export the file into the reports folder
3) Click on the `help` button located at the top of the window bar. This should show the command list in the command box
4) Calling the command `export file` again would result in the error message being shown instead of exporting the graph even tho the graph is already shown

<img width="544" alt="Screenshot 2020-04-09 at 8 32 52 PM" src="https://user-images.githubusercontent.com/54199354/78900248-265e5700-7aa9-11ea-9acb-29a1b4c5dde7.png">

**Comment by XinPei-ng** [comment]
Hi thank you for spotting the error. It has being fixed
