### ISSUE TITLE
No error message is being shown for duplicated exp

### ISSUE THREAD

**Issue by ngzhaoming** [AY1920S2-CS2103T-T10-3/main#237]
As stated in the title, while the exception is being caught in the terminal for duplicated exp, this is not shown in the GUI. Hence, this might confuse the users since they are not greeted with an error message.

<img width="1213" alt="Screenshot 2020-04-09 at 6 31 23 PM" src="https://user-images.githubusercontent.com/54199354/78900539-8b19b180-7aa9-11ea-8432-cc9f3ab34d7e.png">

**Comment by sp-shaopeng** [comment]
we allow duplicate exp
