### ISSUE TITLE
Repeat edit function seems to edit the wrong index

### ISSUE THREAD

**Issue by ngzhaoming** [AY1920S2-CS2103T-T10-3/main#239]
Due to allowing of duplications for the repeat function this has resulted in a potential error with regards to the editing of entries based on the index. As seen in the picture, although I have requested to edit the repeat entry for index 3, it is shown as if data entry at index 2 has been edited instead. this is due to the fact that there is an auto-sort function that sorts the list whenever any common is being called. Nonetheless, I believe this might be flagged as an issue even though the edit function did fulfill its command as instructed. Just be sure to be able to defend yourself if flagged @shaopeng.

<img width="1132" alt="Screenshot 2020-04-09 at 8 14 47 PM" src="https://user-images.githubusercontent.com/54199354/78902736-c4075580-7aac-11ea-8a4d-9ed16256da89.png">

**Comment by sp-shaopeng** [comment]
this is due to auto sorting after editing. Have just update ug.
